name: publish

env:
  CI: true
on:
  push:
    branches:
      - main

jobs:
  release:
    name: publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@simula-labs'

      - name: ci and build
        run: |
          npm ci
          npm run build

      - name: Publish as github package
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GH_DEVELOPER_PAT }}
          NPM_TOKEN: ${{ secrets.GH_DEVELOPER_PAT }}
